
behaviors:
  MyBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    max_steps: 9000000
    time_horizon: 32
    summary_freq: 5000
    checkpoint_interval: 50000
    keep_checkpoints: 100
  